### PR TITLE
gherkin: Do not trim spaces inside a table cell content

### LINKED ISSUE #290: gherkin: Leading and trailing "\n" are trimmed in DataTable cells
After upgrading from cucumber-jvm 1.2.4 to 2.0.1, some of our tests failed.  
We have steps like this:
```
And the text should be
|something\n|
```
The important thing here is the "**\n**" at the end.  
With the older version, the "\n" was retained, but the new one trims it.  
I tracked down the issue and I think it's caused by an old change here: https://github.com/cucumber/gherkin-java/blob/v4.1.3/src/main/java/gherkin/GherkinLine.java#L67  
It's parsing the line from the feature file and this part of the code handle the new line character perfectly: https://github.com/cucumber/gherkin-java/blob/v4.1.3/src/main/java/gherkin/GherkinLine.java#L90  
But at the end of the line(at the "|" char) it trims the string: https://github.com/cucumber/gherkin-java/blob/v4.1.3/src/main/java/gherkin/GherkinLine.java#L86  
It doesn't make too much sense to me, because the original string as the variable name suggests(*trimmedLineText*) is already trimmed, so I think everything inside the "|" characters should remain the same, with all of the white space.

### PR DESCRIPTION
**Pull request by vincent-psarga**
## Summary

If your datatable contains this:

```
| column 1       | column 2                                 | column 3                                            |
| some data     |                    some other data | some\n               other\n                  data  |
```

After parsing, you should get those values:
 - `some data`(white spaces after removed)
 - `some other data`(white spaces before removed)
 -  `some\n               other\n                  data ` (white spaces inside left as it)

Currently, we "may" get `some\nother\ndata` instead/

**UPDATE:** that's not linked to issue #290, I misread the issue ... I'll remove the references in the commits before squashing to avoid having wrong references in the issue.

## TODO

- [x] Add generic example in `gherkin/testdata/good`

## How Has This Been Tested?

With unit tests (and later on acceptance one, but I think the acceptance ones are important to really understand what happens)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] The change has been ported to Java.
- [x] The change has been ported to Ruby.
- [x] The change has been ported to JavaScript.
- [x] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: gherkin/javascript/test/GherkinLineTest.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+import GherkinLine from '../src/GherkinLine'
+
+describe('GherkinLine', function() {
+  function getCellsText(line: string) {
+    const gl = new GherkinLine(line, 1)
+
+    return gl.getTableCells().map(span => span.text)
+  }
+
+  it('getTableCells correctly trims cells content', function() {
```
Comment (aslakhellesoy) [inline gherkin/javascript/test/GherkinLineTest.ts]: Nitpick: Create a nested `describe("#getTableCells()")` block and use one test per assertion. Instead of saying "correctly" (which is open to interpretation), be explicit, such as `it("trims whitespace after")` etc.

File: gherkin/javascript/test/GherkinLineTest.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
+import * as assert from 'assert'
+import GherkinLine from '../src/GherkinLine'
+
+describe('GherkinLine', function() {
```
Comment (aslakhellesoy) [inline gherkin/javascript/test/GherkinLineTest.ts]: We use arrow functions `() => {}` in mocha tests

File: gherkin/javascript/test/GherkinLineTest.ts (hunk 1 above)
Comment (vincent-psarga) [reply gherkin/javascript/test/GherkinLineTest.ts]: Oh nice I did not know we were able to have nested `describe` in mocha, that's great :)

File: gherkin/javascript/test/GherkinLineTest.ts [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+    it('trims white spaces after cell content', () => {
+      assert.deepEqual(getCellsText("|spaces after   |"), ['spaces after'])
+    })
+
+    it('trims white spaces around cell content', () => {
+      assert.deepEqual(getCellsText("|   \t spaces everywhere   \t|"), ['spaces everywhere'])
+    })
+
+    it('does not delete white spaces inside a cell', () => {
```
Comment (luke-hill) [inline gherkin/javascript/test/GherkinLineTest.ts]: not super important. But you could maybe rename this to 

`it does not delete white spaces in the middle of cell content`

**Comment by mpkorstanje** [comment]
So only Go left?

**Comment by mpkorstanje** [comment]
> So only Go and the acceptance tests left?

Looks like I already added acceptances while fixing https://github.com/cucumber/cucumber/pull/891
